ethereum_rpc = "https://ethereum-hoodi-rpc.publicnode.com"
drosera_rpc  = "https://relay.hoodi.drosera.io"
eth_chain_id = 560048
drosera_address = "0x91cB447BaFc6e0EA0F4Fe056F5a9b1F14bb06e5D"

[traps]

[traps.nymph_echo]
# Compiled artifact of the trap
path = "out/NymphEchoTrap.sol/NymphEchoTrap.json"

# MUST be the latest deployed responder
# Responder deployed at block 1879666
response_contract = "0xC2D52BF67A5616e3E736AC3912FC0fF9f0D5d463"

# MUST match responder signature EXACTLY (8 args)
response_function = "respondWithEchoAlert(address,address,bytes32,bytes32,uint256,uint256,uint256,uint256)"

# Drosera recommended defaults
cooldown_period_blocks = 20
min_number_of_operators = 1
max_number_of_operators = 3
block_sample_size = 2

# Private trap
private_trap = true

# Off-chain operator whitelist
whitelist = [
  "0x14e424df0c35686cf58fc7d05860689041d300f6"
]
