ethereum_rpc = "https://ethereum-hoodi-rpc.publicnode.com"
drosera_rpc = "https://relay.hoodi.drosera.io"
eth_chain_id = 560048
drosera_address = "0x91cB447BaFc6e0EA0F4Fe056F5a9b1F14bb06e5D"

[traps]

[traps.nymph_echo]
path = "out/NymphEchoTrap.sol/NymphEchoTrap.json"
response_contract = "0xd4c80c46d8F1e1bdd3Fc548Dd218B343F5C2F0D3"
response_function = "respondWithEchoAlert(address,address,bytes32,bytes32,uint256,uint256,uint256,uint256,string)"
cooldown_period_blocks = 30
min_number_of_operators = 1
max_number_of_operators = 3
block_sample_size = 20
private_trap = true

whitelist = [
    "0x14e424df0c35686cf58fc7d05860689041d300f6",
]
